layout_spectrum: 0.8763441
typography_spectrum: 0.9516129
color:
  saturation: 0.2363935
  lightness: 0.7779934
  brandStrength: 0.8584229
  brandColors:
    - '#160F0B'
    - '#DFE0E0'
    - '#5B5D5C'
  rhythmicContrast: 0.3031586
name: Www.soulcraftsisters.com
